const MAX_BYTES = 5 * 1024 * 1024;
/** Only call with a URL generated by our own Storage client. Never accept a caller URL. */
export async function readStorageImage(url: string): Promise<Uint8Array> {
  const response = await fetch(url, { redirect: "error", signal: AbortSignal.timeout(15_000) });
  if (!response.ok || !response.body) throw new Error("image_download_failed");
  if (!/^image\/(jpeg|png|webp)(;|$)/i.test(response.headers.get("content-type") ?? "")) {
    throw new Error("unsupported_image_type");
  }
  if (Number(response.headers.get("content-length") ?? 0) > MAX_BYTES) throw new Error("image_too_large");
  const reader = response.body.getReader();
  const parts: Uint8Array[] = [];
  let size = 0;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      size += value.byteLength;
      if (size > MAX_BYTES) throw new Error("image_too_large");
      parts.push(value);
    }
  } finally { await reader.cancel(); }
  if (!size) throw new Error("empty_image");
  const result = new Uint8Array(size);
  let offset = 0;
  for (const part of parts) { result.set(part, offset); offset += part.length; }
  return result;
}
