-- ============================================================
-- rpc_check_in — historical bootstrap placeholder (run order 5)
--
-- This file originally defined public.rpc_check_in(p_token text) using a
-- plaintext lookup against the deprecated lanes.lane_qr_token column, with
-- no token hashing, no expiry/revocation checks, and no security_events
-- logging.
--
-- ⚠ SOURCE OF TRUTH: rpc_check_in is now defined by:
--   - scripts/qr-token-hardening.sql (run order 13) — bootstraps the
--     lane_qr_tokens table and provides the first hash-based definition.
--   - scripts/security-cleanup.sql   (run order 19) — final, hardened,
--     hash-only definition. THIS is the production source of truth.
--
-- Do NOT add a CREATE OR REPLACE FUNCTION public.rpc_check_in here. Doing so
-- would reintroduce the insecure plaintext lane_qr_token lookup if this
-- script is ever (re-)run after scripts 13/19. This file is kept only so the
-- numbered run order in README.md stays stable; it is a no-op.
--
-- Called from the app as: supabase.rpc("rpc_check_in", { p_token: "..." })
-- ============================================================
